### ISSUE TITLE
Getting Kafka-headers using the builtin Kafka connector

### ISSUE THREAD

**Issue by hariso** [ConduitIO/conduit-connector-kafka#125]
### Discussed in https://github.com/ConduitIO/conduit/discussions/1446

<div type='discussions-op-text'>

<sup>Originally posted by **morethom** March 18, 2024</sup>
Hi! 

Title says it all, I've been trying to migrate from Kafka-connect to Conduit for our replicators and find myself needing the Kafka headers from the messages coming from the source. I can't seem to find support for that and don't necessarily want to rewrite the kafka connector just for this. As anyone been able to get this data and/or is there plans for futur support. 

Thanks!</div>

**Comment by simonl2002** [comment]
Looks like multiple folks want this, and it should be fairly low-effort so pulling it in to current release.
@maximus321
@morethom
