### ISSUE TITLE
Feature: Ability to specific Consumer Group for Source Connector

### ISSUE THREAD

**Issue by ahmeroxa** [ConduitIO/conduit-connector-kafka#47]
### Feature description

Users should be able to specify the Consumer Group ID to be used by the Source Connector (and the underlying Kafka Consumer).

This will enable some valuable use cases such as scaling via multiple Conduit instances as well as recovery (where I can create a new instance and have it continue where the previous consumer ended).

**Comment by hariso** [comment]
Maybe we can add the additional details in this ticket: https://github.com/ConduitIO/conduit/issues/142, since it was already triaged?

**Comment by hariso** [comment]
@ahmeroxa :+1: we did move some connector specific issues into the respective repos, so we may do that for this one too.
